server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: helloworld-service
          uri: http://localhost:8081/helloworld
          predicates:
            - Path=/helloworld
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 25
                redis-rate-limiter.burstCapacity: 50
                redis-rate-limiter.requestedTokens: 1
